### ISSUE TITLE
Embeds truncated on mobile

### ISSUE THREAD

**Issue by jdsaphir** [dylanpiera/CodenameIndigo#10]
Long embeds (like those containing the team) are truncated on mobile.
Possible solution would be to send an embed per Pokémon.
![issue](https://user-images.githubusercontent.com/31666847/35883103-79853db6-0b86-11e8-9520-31a612847864.png)
![screenshot_20180206-213952](https://user-images.githubusercontent.com/31666847/35883157-a47b8b9c-0b86-11e8-8891-5ad4adf386df.png)

**Comment by dylanpiera** [comment]
Possible solutions:

- Embed per Pokemon
Is possible but would be really heavy on the gateway (aka bad for the bot) and would spam the channel.

- Mobile version of the commands
would send the result in a PM to the user in text to not clutter public channels

- Other?

Thoughts?

**Comment by dragonnataku** [comment]
Maybe all of them should be via pm to not spam the channel.  We should check if via pm still truncates on mobile

**Comment by dylanpiera** [comment]
They do. Just checked.

**Comment by dylanpiera** [comment]
> Saphir - Today at 11:31 PM
just put the team in a codeblock instead of an embed

This is why we keep Saph around. He's brilliant 😛 

Will implement tomorrow.
