### ISSUE TITLE
Bracket DB storage

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#26]
The Problem
-----------
Just realized, we need to store the brackets in the database in some way, so the website can also call upon it.

Details
-------
@jdsaphir wanna design a table for this?

**Comment by jdsaphir** [comment]
I will.

**Comment by jdsaphir** [comment]
What I'm planning:
At the beginning of round 1 (or the end of registration), the matches are randomly assigned, and stored in
**battles**
- bid INT PRIMARY AI (Automatically filled by MySQL)
- tid INT (The tournament ID)
- round INT (The round for this match)
- player1 BIGINT (The first player's ID)
- player2 BIGINT (The second player's ID)
- winner INT (The winner: 0 if not yet battled, 1 for the first player, 2 for the second. I'd say rematch in case of draw but see with DN.)

At the beginning of round 2 (or the end of round 1), the winners are randomly matched up against another winner, stored the same way but with 2 as the round.
Then the winners are matched up with 3 as the round and so on until there's only one winner.

But of course, if the number of players at the beginning isn't a power of 2... 🤔 

![image](https://user-images.githubusercontent.com/31666847/36077555-9f8e8ad2-0f6c-11e8-84c3-374a19411d9c.png)

**Comment by dylanpiera** [comment]
> player1 BIGINT (The first player's ID)
> player2 BIGINT (The second player's ID)

Wouldn't these be the player's PIDs (aka no need for BIGINT)?

**Comment by jdsaphir** [comment]
It would.
**battles**
- bid INT PRIMARY AI (Automatically filled by MySQL)
- tid INT (The tournament ID)
- round INT (The round for this match)
- player1 INT (The first player's pid (from *participants*))
- player2 INT (The second player's pid (from *participants*))
- winner INT (The winner: 0 if not yet battled, 1 for the first player, 2 for the second. I'd say rematch in case of draw but see with DN.)
