### ISSUE TITLE
Administrative Logging

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#28]
Details
-------
Log any administrative action we have.

**Comment by jdsaphir** [comment]
Assigning myself to design a table.
Will probably be:
**adminlog**
- lid INT PRIMARY AI (Automatically filled by MySQL)
- uid BIGINT (The admin's ID)
- aid INT (A code representing the action taken by the admin.)

**adminactions**
- aid INT PRIMARY AI (Automatically filled by MySQL)
- description VARCHAR(64) (A description of the action.)

That would allow both the bot and the website to show the same description for each action, and prevent filling the action with the same text every time.

Tell me if you think there should be something else.
