### ISSUE TITLE
Lookup command (maybe others?) requires quotes

### ISSUE THREAD

**Issue by jdsaphir** [dylanpiera/CodenameIndigo#31]
Even though the lookup command has only one parameter (afaik), it requires quotes when said parameter contains a space.
Example: ?lookup Water Max#1890 will return "The user Water Max#1890 doesn't exist.", while ?lookup "Water Max#1890" will work properly.

Should also check other commands don't have this issue.

*Don't fix if ?lookup allows for two parameters.*

**Comment by dylanpiera** [comment]
It uses param of type `iuser` adding the [Remainder] tag will fix it.
