### ISSUE TITLE
Should Showdown Input be Checked in any way shape or form?

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/CodenameIndigo#4]

**Comment by jdsaphir** [comment]
It should be checked that it is not empty.
For the rest... If the entered team is not in accordance with OU rules, they won't be able to participate in the battle, so they'll be forfeited. I think Showdown's check is enough.
"Easy" things to check would be that there actually are six Pokémon, all level 100 without two of the same species, but I don't really think it necessary to check.

**Comment by dylanpiera** [comment]
I mean fear rattata are fair game. So checking for lvl 100 is unnecessary imo

Checking for 6 would be possible, but I don't think it's necessary. If your team doesn't comply with the rules you're automatically disqualified
